name: CI

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff mypy fastapi sqlalchemy

      - name: Check code style locally
        run: |
          ruff check src/
          mypy src/

      - name: Run tests
        run: |
          docker compose --env-file .env.test run --rm -e PYTHONPATH=/opt/app app pytest tests/ -v
